project_id = "jkcdwxkqzohibsxglhyk"

[functions.create-user]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.cloudinary-upload]
verify_jwt = false

[functions.remove-bg]
verify_jwt = false
